version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: readlater_db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: readlater_bot
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: